image: python:3.7-slim-buster

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - test
  - build

.pip:
  script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - . venv/bin/activate

test:
  stage: test
  extends: .pip
  script:
    - pip install flake8
    - flake8

run:
  stage: build
  extends: .pip
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - TWINE_CERT=$KNUT_CA TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
